" Configuration file for vim
set modelines=0     " CVE-2007-2438

"Normally we use vim-extensions. If you want true vi-compatibility
"remove change the following statements
set nocompatible    " Use Vim defaults instead of 100% vi compatibility
set backspace=2     " more powerful backspacing

" Don't write backup file if vim is being called by "crontab -e"
au BufWrite /private/tmp/crontab.* set nowritebackup
" Don't write backup file if vim is being called by "chpass"
au BufWrite /private/etc/pw.* set nowritebackup

if has("syntax")
    syntax on
endif

set ignorecase
set incsearch
set mouse=a
set selection=exclusive
set selectmode=mouse,key
set showmatch
set cindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set shellslash
set grepprg=grep\ -nH\ $*
set foldmethod=manual
set foldlevelstart=99999999
set list
set listchars=tab:\|\ ,
setlocal foldlevel=1
filetype indent on
filetype on
syntax on
syntax enable
filetype plugin on
set nu
set autoindent
set autoread
set autowrite
"set t_Co=256
"set background=dark
"colorscheme solarized

"key maps

nmap <C-k> <C-w>k
nmap <C-j> <C-w>j
nmap <C-h> <C-w>h
nmap <C-l> <C-w>l

nmap _ :bp<CR>
nmap + :bn<CR>

nnoremap o o<Esc>
nnoremap O O<Esc>
noremap H ^
noremap L $
noremap $ L
noremap ^ H

map <F2> :res +5<CR>
map <F3> :res -5<CR>
map <F4> :vertical res +5<CR>
map <F5> :vertical res -5<CR>

vmap <C-c> "0y
nmap <C-v> "0p
imap <C-v> <Esc>"0pa

nnoremap x :AutoXDelete<CR>

nmap <silent> <c-n> :NERDTreeToggle<CR>

:inoremap ( ()<ESC>i
:inoremap ) <c-r>=ClosePair(')')<CR>
:inoremap { {}<ESC>i
:inoremap } <c-r>=ClosePair('}')<CR>
:inoremap [ []<ESC>i
:inoremap ] <c-r>=ClosePair(']')<CR>
:inoremap <CR> <CR>;<ESC>:AutoBreak<CR>"_cl
:inoremap <BS> <ESC>:AutoBSDelete<CR>a

"Easymotion
:let mapleader=","
let g:EasyMotion_leader_key= '<Leader>'

let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1

let g:neocomplcache_enable_at_startup = 1
let g:neocomplcache_enable_auto_select = 1


"functions

function ClosePair(char)
if getline('.')[col('.') - 1] == a:char
return "\<Right>"
else
return a:char
endif
endf

command! AutoXDelete call AutoXDelete()
function! AutoXDelete()
if ((getline('.')[col('.') - 1] == '(') && (getline('.')[col('.')] == ')')) || ((getline('.')[col('.') - 1] == '[') && (getline('.')[col('.')] == ']')) || ((getline('.')[col('.') - 1] == '{') && (getline('.')[col('.')] == '}'))
    execute "normal! xx"
else
    execute "normal! x"
endif
endfunction

command! AutoBSDelete call AutoBSDelete()
function! AutoBSDelete()
if ((getline('.')[col('.') - 1] == '(') && (getline('.')[col('.')] == ')')) || ((getline('.')[col('.') - 1] == '[') && (getline('.')[col('.')] == ']')) || ((getline('.')[col('.') - 1] == '{') && (getline('.')[col('.')] == '}'))
    execute "normal! la\<BS>\<BS>"
else
    execute "normal! a\<BS>"
endif
endfunction

command! AutoBreak call AutoBreak()
function! AutoBreak()
if (getline('.')[col('.')] == '}')
    execute "normal! cl\<ESC>kA\<CR>;"
endif
endfunction

filetype plugin indent on

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

"plugins

Plugin 'EasyMotion'
Plugin 'The-NERD-tree'
Plugin 'The-NERD-Commenter'
Plugin 'bufexplorer.zip'
Plugin 'bufkill.vim'
Plugin 'minibufexpl.vim'
Plugin 'sudo.vim'
Plugin 'neocomplcache'
Plugin 'surround.vim'
Plugin 'JavaScript-syntax'
Plugin 'a.vim'

call vundle#end()
